//////////////////////////////////////
// identical maps: BG0170
// BG0013 BG0015 BG0160 BG0170 BG0710 BG0716 BG0802 BG0814 BG1204 BG1214 BG1309 BG1317
//////////////////////////////////////

SPRINT identical_area "BG0170"

PATCH_IF FILE_EXISTS ~%MOD_FOLDER%/base/are_patch/%identical_area%_are.tpa~ BEGIN // add animation for braziers, candles ...
	PATCH_INCLUDE ~%MOD_FOLDER%/base/are_patch/%identical_area%_are.tpa~
END
