//////////////////////////////////////
// identical maps: BG0167
// BG0008 BG0010 BG0157 BG0167 BG0302 BG0619 BG0707 BG0713 BG0805 BG1107 BG1205 BG1209 BG1314 BG3309 BG3311 BG3323 BG3329 BG3333 BG3347 BG3355
//////////////////////////////////////

SPRINT identical_area "BG0167"

PATCH_IF FILE_EXISTS ~%MOD_FOLDER%/base/are_patch/%identical_area%_are.tpa~ BEGIN // add animation for braziers, candles ...
	PATCH_INCLUDE ~%MOD_FOLDER%/base/are_patch/%identical_area%_are.tpa~
END
